=== ministryofjustice/laa-crime-applications-adaptor/crime-applications-adaptor/src/main/resources/schemas/criminalapplicationsdatastore/maat_application_external.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "ministryofjustice/laa-criminal-legal-aid-schemas/main/schemas/1.0/maat_application.json",
  "title": "An application for criminal legal aid for MAAT",
  "description": "Attributes of a criminal legal aid application for MAAT",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "schema_version": { "type": "number" },
    "reference": { "type": "integer" },
    "application_type": { "type": "string", "enum": ["initial", "post_submission_evidence", "change_in_financial_circumstances"] },
    "submitted_at": { "type": "string", "format": "date-time", "customDateTimePattern": "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
    "declaration_signed_at": { "type": "string", "format": "date-time", "customDateTimePattern": "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
    "date_stamp": { "type": "string", "format": "date-time", "customDateTimePattern": "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
    "ioj_bypass": {
      "description": "Indicates whether the Interests of Justice page was skipped or not",
      "type": "boolean"
    },
    "means_passport": {
      "type": "array",
      "items": { "type": "string", "enum": ["on_age_under18", "on_benefit_check"] }
    },
    "provider_details": {
      "$ref": "#/definitions/provider"
    },
    "client_details": {
      "type": "object",
      "properties": {
        "applicant": {
          "type": "object",
          "properties": {
            "first_name": { "type": "string" },
            "last_name": { "type": "string" },
            "other_names": { "type": ["string", "null"] },
            "date_of_birth": { "type": "string", "format": "date" },
            "nino": { "type": ["string", "null"] },
            "benefit_type": { "type": ["string", "null"], "enum": ["universal_credit", "guarantee_pension", "jsa", "esa", "income_support", null] },
            "telephone_number": { "type": ["string", "null"] },
            "correspondence_address_type": { "type": "string", "enum": ["other_address", "home_address", "providers_office_address"] },
            "home_address": { "$ref": "#/definitions/address" },
            "correspondence_address": { "$ref": "#/definitions/address" }
          },
          "required": ["first_name", "last_name", "date_of_birth", "correspondence_address_type"]
        }
      },
      "required": ["applicant"]
    },
    "case_details": {
      "type": "object",
      "properties": {
        "urn": { "type": ["string", "null"] },
        "case_type": {
          "type": "string",
          "enum": [
            "summary_only",
            "either_way",
            "indictable",
            "already_in_crown_court",
            "committal",
            "appeal_to_crown_court",
            "appeal_to_crown_court_with_changes"
          ]
        },
        "appeal_maat_id": { "type": ["string", "null"] },
        "appeal_lodged_date": { "type": ["string", "null"], "format": "date" },
        "appeal_with_changes_details": { "type": ["string", "null"] },
        "offence_class": { "type": ["string", "null"], "enum": ["A", "K", "G", "B", "I", "J", "D", "C", "H", "F", "E", null] },
        "hearing_court_name": { "type": "string" },
        "hearing_date": { "type": "string", "format": "date" }
      },
      "required": ["case_type", "hearing_court_name", "hearing_date", "offence_class"]
    },
    "means_details": {
      "type": "object",
      "properties": {
        "income_details": {
          "type": "object",
          "properties": {
            "benefits": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "child",
                      "working_or_child_tax_credit",
                      "universal_credit",
                      "incapacity",
                      "industrial_injuries_disablement",
                      "jsa",
                      "other"
                    ]
                  },
                  "amount": {
                    "type": "integer"
                  },
                  "frequency": {
                    "type": "string",
                    "enum": ["week", "fortnight", "four_weeks", "month", "annual"]
                  },
                  "details": {
                    "anyOf": [
                      {
                        "type": "null"
                      },
                      {
                        "type": "string"
                      }
                    ]
                  }
                },
                "required": ["type", "amount", "frequency"]
              }
            },
            "employment_type": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": ["employed", "self-employed", "business_partnership", "director", "shareholder", "not_working"]
              }
            },
            "employment_details": {
              "type": "object",
              "properties": {
                "paye": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "amount": {
                        "type": "integer"
                      },
                      "date": {
                        "type": "string",
                        "format": "date"
                      },
                      "deductions": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "type": {
                              "type": "string"
                            },
                            "amount": {
                              "type": "integer"
                            }
                          },
                          "required": ["type", "amount"]
                        }
                      }
                    },
                    "required": ["amount", "date", "deductions"]
                  }
                },
                "other": {
                  "type": "object",
                  "properties": {
                    "amount": {
                      "type": "integer"
                    },
                    "details": {
                      "type": "string"
                    }
                  },
                  "required": ["amount", "details"]
                },
                "businesses": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "address": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "lookup_id": {
                              "anyOf": [
                                {
                                  "type": "null"
                                },
                                {
                                  "type": "string"
                                }
                              ]
                            },
                            "address_line_one": {
                              "type": "string"
                            },
                            "address_line_two": {
                              "anyOf": [
                                {
                                  "type": "null"
                                },
                                {
                                  "type": "string"
                                }
                              ]
                            },
                            "city": {
                              "type": "string"
                            },
                            "country": {
                              "type": "string"
                            },
                            "postcode": {
                              "type": "string"
                            }
                          },
                          "required": ["lookup_id", "address_line_one", "address_line_two", "city", "country", "postcode"]
                        }
                      },
                      "last_two_years_tax_liability": {
                        "type": "integer"
                      },
                      "total_turnover": {
                        "type": "integer"
                      },
                      "total_drawing": {
                        "type": "integer"
                      },
                      "total_profit": {
                        "type": "integer"
                      },
                      "director_salary": {
                        "type": "integer"
                      },
                      "share": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "name",
                      "address",
                      "last_two_years_tax_liability",
                      "total_turnover",
                      "total_drawing",
                      "total_profit",
                      "director_salary",
                      "share"
                    ]
                  }
                }
              },
              "required": ["paye"]
            },
            "other_income": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "private_pension",
                      "state_pension",
                      "maintenance",
                      "interest",
                      "student",
                      "board_from_family",
                      "rent",
                      "friends_and_family",
                      "other"
                    ]
                  },
                  "amount": {
                    "type": "integer"
                  },
                  "frequency": {
                    "type": "string",
                    "enum": ["week", "fortnight", "four_weeks", "month", "annual"]
                  },
                  "details": {
                    "anyOf": [
                      {
                        "type": "null"
                      },
                      {
                        "type": "string"
                      }
                    ]
                  }
                },
                "required": ["type", "amount", "frequency"]
              }
            },
            "total": {
              "type": "integer"
            },
            "dependants": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "age": {
                    "type": "integer",
                    "exclusiveMaximum": 18
                  }
                },
                "required": ["age"]
              }
            }
          },
          "required": []
        },
        "outgoings_details": {
          "type": "object",
          "properties": {
            "outgoings": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": ["housing", "council_tax", "childcare", "maintenance", "legal_aid"]
                  },
                  "amount": {
                    "type": "integer"
                  },
                  "frequency": {
                    "type": "string",
                    "enum": ["week", "fortnight", "four_weeks", "month", "annual"]
                  },
                  "details": {
                    "anyOf": [
                      {
                        "type": "null"
                      },
                      {
                        "type": "string"
                      }
                    ]
                  }
                },
                "required": ["type", "amount", "frequency"]
              }
            },
            "housing_payment_type": {
              "anyOf": [
                {
                  "type": "null"
                },
                {
                  "type": "string",
                  "enum": ["rent", "mortgage", "board_lodgings", "none"]
                }
              ]
            }
          },
          "required": []
        }
      }
    }
  },
  "required": [
    "id",
    "schema_version",
    "reference",
    "application_type",
    "submitted_at",
    "date_stamp",
    "declaration_signed_at",
    "ioj_bypass",
    "means_passport",
    "provider_details",
    "client_details",
    "case_details"
  ],
  "definitions": {
    "provider": { "$ref": "general/provider.json" },
    "address": { "$ref": "general/address.json" }
  }
}

=== ministryofjustice/laa-crime-applications-adaptor/crime-applications-adaptor/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_6000308.json
{
  "id": "620954f5-54b2-4b02-88b0-f6e4165cb6d3",
  "schema_version": 1.0,
  "reference": 6000308,
  "application_type": "initial",
  "means_passport": ["on_benefit_check"],
  "submitted_at": "2022-10-24T09:50:04.019Z",
  "date_stamp": "2022-10-24T09:50:04.019Z",
  "declaration_signed_at": "2022-10-24T09:50:04.019Z",
  "provider_details": {
    "office_code": "0Z981E",
    "provider_email": "abenn@quinn-melville.co.uk",
    "legal_rep_first_name": "Karl",
    "legal_rep_last_name": "Kent",
    "legal_rep_telephone": "07712345678"
  },
  "client_details": {
    "applicant": {
      "date_of_birth": "1980-01-10",
      "nino": "JA293483A",
      "benefit_type": "universal_credit",
      "telephone_number": "",
      "correspondence_address_type": "providers_office_address",
      "last_name": "Walker",
      "first_name": "Pat",
      "other_names": ""
    }
  },
  "case_details": {
    "urn": "",
    "case_type": "summary_only",
    "offence_class": "H",
    "hearing_court_name": "Cardiff Magistrates' Court",
    "hearing_date": "2024-09-27"
  },
  "means_details": {
    "income_details": {
      "benefits": [
        {
          "type": "child",
          "amount": 200,
          "frequency": "month",
          "details": "Details about child benefit"
        },
        {
          "type": "incapacity",
          "amount": 300,
          "frequency": "fortnight",
          "details": null
        },
        {
          "type": "universal_credit",
          "amount": 500,
          "frequency": "week",
          "details": null
        }
      ],
      "employment_type": ["not_working"],
      "other_income": [
        {
          "type": "private_pension",
          "amount": 13000,
          "frequency": "annual",
          "details": "Details about private pension"
        },
        {
          "type": "interest",
          "amount": 700,
          "frequency": "four_weeks",
          "details": null
        },
        {
          "type": "rent",
          "amount": 635,
          "frequency": "month",
          "details": null
        }
      ],
      "dependants": [
        {
          "age": 8
        },
        {
          "age": 9
        },
        {
          "age": 17
        }
      ]
    }
  },
  "ioj_bypass": true
}

=== ministryofjustice/laa-crime-applications-adaptor/crime-applications-adaptor/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_unemployed.json
{
  "id": "696dd4fd-b619-4637-ab42-a5f4565bcf4a",
  "schema_version": 1,
  "reference": 6000001,
  "application_type": "initial",
  "submitted_at": "2022-10-24T09:50:04.019Z",
  "date_stamp": "2022-10-24T09:50:04.019Z",
  "declaration_signed_at": "2022-10-24T09:50:04.019Z",
  "means_passport":[],
  "provider_details": {
    "office_code": "1A123B",
    "provider_email": "provider@example.com",
    "legal_rep_first_name": "John",
    "legal_rep_last_name": "Doe",
    "legal_rep_telephone": "123456789"
  },
  "client_details": {
    "applicant": {
      "first_name": "Kit",
      "last_name": "Pound",
      "nino": "AJ123456C",
      "date_of_birth": "2011-06-09",
      "telephone_number": "07771231231",
      "correspondence_address_type": "home_address",
      "home_address": {
        "lookup_id": null,
        "address_line_one": "1 Road",
        "address_line_two": "Village",
        "city": "Some nice city",
        "country": "United Kingdom",
        "postcode": "SW1A 2AA"
      },
      "correspondence_address": null
    }
  },
  "case_details": {
    "urn": "",
    "case_type": "appeal_to_crown_court",
    "offence_class": "A",
    "appeal_maat_id": null,
    "hearing_court_name": "Cardiff Magistrates' Court",
    "hearing_date": "2024-11-11",
    "appeal_lodged_date": "2021-10-25"
  },
  "means_details": {
    "income_details": {
      "benefits": [
        {
          "type": "child",
          "amount": 200,
          "frequency": "month",
          "details": "Details about child benefit"
        },
        {
          "type": "incapacity",
          "amount": 300,
          "frequency": "fortnight",
          "details": null
        },
        {
          "type": "universal_credit",
          "amount": 500,
          "frequency": "week",
          "details": null
        }
      ],
      "employment_type": [
        "not_working"
      ],
      "other_income": [
        {
          "type": "private_pension",
          "amount": 13000,
          "frequency": "annual",
          "details": "Details about private pension"
        },
        {
          "type": "interest",
          "amount": 700,
          "frequency": "four_weeks",
          "details": null
        },
        {
          "type": "rent",
          "amount": 635,
          "frequency": "month",
          "details": null
        }
      ],
      "dependants": [
        {
          "age": 8
        },
        {
          "age": 9
        },
        {
          "age": 17
        }
      ]
    },
    "outgoings_details" : {
      "outgoings": [
        {
          "type": "council_tax",
          "amount": 100,
          "frequency": "annual"
        },
        {
          "type": "childcare",
          "amount": 200,
          "frequency": "month"
        },
        {
          "type": "maintenance",
          "amount": 400,
          "frequency": "four_weeks"
        },
        {
          "type": "legal_aid",
          "amount": 500,
          "frequency": "fortnight"
        },
        {
          "type": "housing",
          "amount": 601,
          "frequency": "week",
          "details": "Details about housing"
        }
      ],
      "housing_payment_type": "board_lodgings"
    }
  },
  "ioj_bypass": true
}

=== ministryofjustice/laa-crime-applications-adaptor/crime-applications-adaptor/application/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_6000308.json
{
  "id": "620954f5-54b2-4b02-88b0-f6e4165cb6d3",
  "schema_version": 1.0,
  "reference": 6000308,
  "application_type": "initial",
  "means_passport": ["on_benefit_check"],
  "submitted_at": "2022-10-24T09:50:04.019Z",
  "date_stamp": "2022-10-24T09:50:04.019Z",
  "declaration_signed_at": "2022-10-24T09:50:04.019Z",
  "provider_details": {
    "office_code": "0Z981E",
    "provider_email": "abenn@quinn-melville.co.uk",
    "legal_rep_first_name": "Karl",
    "legal_rep_last_name": "Kent",
    "legal_rep_telephone": "07712345678"
  },
  "client_details": {
    "applicant": {
      "date_of_birth": "1980-01-10",
      "nino": "JA293483A",
      "benefit_type": "universal_credit",
      "telephone_number": "",
      "correspondence_address_type": "providers_office_address",
      "last_name": "Walker",
      "first_name": "Pat",
      "other_names": ""
    }
  },
  "case_details": {
    "urn": "",
    "case_type": "summary_only",
    "offence_class": "H",
    "hearing_court_name": "Cardiff Magistrates' Court",
    "hearing_date": "2024-09-27"
  },
  "means_details": {
    "income_details": {
      "income_benefits": [
        {
          "payment_type": "child",
          "amount": 20000,
          "frequency": "month",
          "details": "Details about child benefit"
        },
        {
          "payment_type": "incapacity",
          "amount": 30000,
          "frequency": "fortnight",
          "details": null
        },
        {
          "payment_type": "universal_credit",
          "amount": 50000,
          "frequency": "week",
          "details": null
        }
      ],
      "employment_type": ["not_working"],
      "income_payments": [
        {
          "payment_type": "private_pension",
          "amount": 1300000,
          "frequency": "annual",
          "details": "Details about private pension"
        },
        {
          "payment_type": "interest_investment",
          "amount": 700000,
          "frequency": "four_weeks",
          "details": null
        },
        {
          "payment_type": "other",
          "amount": 63500,
          "frequency": "month",
          "details": null
        }
      ],
      "dependants": [
        {
          "age": 8
        },
        {
          "age": 9
        },
        {
          "age": 17
        }
      ]
    }
  },
  "ioj_bypass": true
}
